### ISSUE TITLE
Cannot find module '@mapbox/geo-viewport'

### ISSUE THREAD

**Issue by ThSGM** [crofty/openmap-local-svg-maps#1]
Hi crofty,

Thanks for providing this script. I'm new to scripting in general and am trying to get this working. Upon running `ruby script.rb` I get the error

```
module.js:471
    throw err;
    ^

Error: Cannot find module '@mapbox/geo-viewport'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:19
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:358:29)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
```

Do I need a ruby package? 

I do see that there is something [like this](https://github.com/mapbox/geo-viewport) but I'm not sure what I'm supposed to do with it. I did try issuing the command  `npm install --save @mapbox/geo-viewpoint` but it returns

```
npm ERR! code E404
npm ERR! 404 Not Found: @mapbox/geo-viewpoint@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myusername/.npm/_logs/2018-08-25T17_00_36_091Z-debug.log
```

I'm running Mac OS 10.11

**Comment by crofty** [comment]
@ThSGM I think you might just need to run an `npm install` before running the ruby script

**Comment by ThSGM** [comment]
@crofty 

Hi, it looks like I have both node and npm installed: 

```
$ which node
/usr/local/bin/node

$ node -v
v6.10.1

$ which npm
/usr/local/bin/npm

$ npm -v
6.2.0
```

**Comment by crofty** [comment]
@ThSGM I think you will just need to run the command `npm install` from the root of this project.  That will look at the `package.json` file and it should install the required npm packages.

**Comment by ThSGM** [comment]
@crofty 

>  from the root of this project. 

What project were your referring to? There isn't a package.json in the root of `openmap-local-svg-maps`. Sorry if I'm missing something obvious.

**Comment by crofty** [comment]
@ThSGM sorry, I hadn't committed the package.json. It's there now.  However, looking back at the script it's not a portable script, there are a few hardcoded bits that are specific for my machine.
I put it up on Github for reference, but you're going to need to tweak it a bit to get it running for you.

**Comment by ThSGM** [comment]
@crofty 

Okay, so npm install seemed to run fine now. 

Upon the first run of `ruby script.rb` I get

```
$ ruby script.rb
  rm -rf output
  mkdir output
    ruby build_vrt.rb Road output/OpenMap-Road.vrt
Traceback (most recent call last):
  File "ogr2vrt.py", line 32, in <module>
    from osgeo import osr, ogr, gdal
ModuleNotFoundError: No module named 'osgeo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ogr2vrt.py", line 34, in <module>
    import osr, ogr, gdal
ModuleNotFoundError: No module named 'osr'
build_vrt.rb:13:in `initialize': No such file or directory - output/OpenMap-Road.vrt (Errno::ENOENT)
	from build_vrt.rb:13:in `open'
	from build_vrt.rb:13:in `<main>'
script.rb:5:in `run_command': Command failed (RuntimeError)
	from script.rb:46:in `block in <main>'
	from script.rb:40:in `each'
```

I assume that had something with not having some packages. I ran

`conda install gdal`

That seemed to get me past the module commands at least. But now, I get:


```
$ ruby script.rb
  rm -rf output
  mkdir output
    ruby build_vrt.rb Road output/OpenMap-Road.vrt
Traceback (most recent call last):
  File "ogr2vrt.py", line 122, in <module>
    for layer in src_ds:
TypeError: 'NoneType' object is not iterable
build_vrt.rb:13:in `initialize': No such file or directory - output/OpenMap-Road.vrt (Errno::ENOENT)
	from build_vrt.rb:13:in `open'
	from build_vrt.rb:13:in `<main>'
script.rb:5:in `run_command': Command failed (RuntimeError)
	from script.rb:46:in `block in <main>'
	from script.rb:40:in `each'
	from script.rb:40:in `<main>'
```

Not sure what the error above is.

**Comment by crofty** [comment]
Have you downloaded the Openmap data?  If so, you'll then need to change the following paths to point at the files:
https://github.com/crofty/openmap-local-svg-maps/blob/master/build_vrt.rb#L5
https://github.com/crofty/openmap-local-svg-maps/blob/master/script.rb#L51

**Comment by ThSGM** [comment]
So I think I understand the first part. I downloaded the data from[ OS Open Map - Local in format ESRI Shape](https://www.ordnancesurvey.co.uk/opendatadownload/products.html#OPMPLC) for a particular region. The zip file contained a folder with two subfolders `sp/data' (with a bunch of shp files) and `sp/doc'. So I changed the `build_vrt.rb' code to include:

```
base_dir   = '/Users/myusername/mapdata/sp'
shapefiles = Dir.glob("#{base_dir}/*/*_#{layer_name}.shp")
```

That seemed to get rid of the error, and now I have one pointing to `script.rb` and the line you indicated. I thought I needed docker, so 

`brew install docker`

Now I get the error: 

```
$ ruby script.rb
  rm -rf output
  mkdir output
    ruby build_vrt.rb Road output/OpenMap-Road.vrt
  docker run  -v $(pwd):/gdal -v /mnt/NAS/Maptrail:/mnt/NAS/Maptrail -w /gdal geographica/gdal2       ogr2ogr         -f "GeoJSON"         -t_srs EPSG:4326         -s_srs "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.999601 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs +nadgrids=./OSTN02_NTv2.gsb"         -spat -0.1355266571044922 51.51216124955517 0.06514549255371094 51.42126249859379         -spat_srs EPSG:4326         -clipdst -0.1355266571044922 51.51216124955517 0.06514549255371094 51.42126249859379         output/Road.geojson output/OpenMap-Road.vrt
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
script.rb:5:in `run_command': Command failed (RuntimeError)
	from script.rb:50:in `block in <main>'
	from script.rb:40:in `each'
	from script.rb:40:in `<main>'

```

Do I have to do something with docker?

I also don't understand this line at all:

docker run  -v $(pwd):/gdal -v /mnt/NAS/Maptrail:/mnt/NAS/Maptrail -w /gdal geographica/gdal2 \

What is gdal? 

What is in the /mnt/NAS/Maptrail directory? Do I need additional files? 

What is geographica/gdal2?
